const SetupBtn = [
  {
    key: 'elementId',
    value: '00000000-0000-0a79-ffff-ffff000006b5',
    name: 'elementId',
  },
  {key: 'index', value: '0', name: 'index'},
  {key: 'package', value: 'com.safetrack.kaiduconfiguration', name: 'package'},
  {key: 'class', value: 'android.view.ViewGroup', name: 'class'},
  {key: 'text', value: '', name: 'text'},
  {
    key: 'content-desc',
    value: 'Setup this Kaidu Scanner',
    name: 'content-desc',
  },
  {key: 'resource-id', value: 'Setup this Kaidu Scanner', name: 'resource-id'},
  {key: 'checkable', value: 'false', name: 'checkable'},
  {key: 'checked', value: 'false', name: 'checked'},
  {key: 'clickable', value: 'true', name: 'clickable'},
  {key: 'enabled', value: 'true', name: 'enabled'},
  {key: 'focusable', value: 'true', name: 'focusable'},
  {key: 'focused', value: 'false', name: 'focused'},
  {key: 'long-clickable', value: 'false', name: 'long-clickable'},
  {key: 'password', value: 'false', name: 'password'},
  {key: 'scrollable', value: 'false', name: 'scrollable'},
  {key: 'selected', value: 'false', name: 'selected'},
  {key: 'bounds', value: '[48,1353][501,1486]', name: 'bounds'},
  {key: 'displayed', value: 'true', name: 'displayed'},
];
