workflows:
    react-native:
        name: reactnativeappsigning
        environment:
            vars:
                XCODE_WORKSPACE: "kaidusimple.xcworkspace"
                XCODE_SCHEME: "simple"
                APP_ID: 1598671114
            node: latest
            groups:
            - module_credentials
        scripts:
            - yarn install
            - echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
            - |
                # build Android
                cd android
                ./gradlew assembleDebug
            - |
                # build iOS
                cd ios
                pod install
                xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - android/app/build/outputs/**/**/*.apk
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
